"""
Startup Blueprint Screen.
Recreates the complete Startup Blueprint screen from the UI reference image.
Includes quick PDF download and navigable sections.
"""
from typing import Optional, Dict, Any
import streamlit as st
from database.models import Startup, StartupAnalysis, DynamicRoadmap
from services.report_service import ReportService
from ui.styles import get_width_kwargs


def render_blueprint_view(
    startup: Optional[Startup],
    analysis: Optional[StartupAnalysis],
    roadmap: Optional[DynamicRoadmap],
):
    """
    Renders the Startup Blueprint view matching the reference design.
    """
    if not startup:
        st.info("Please create or select a startup to view the blueprint.")
        return

    if not analysis:
        st.info(f"Venture Blueprint for '{startup.name}' has not been generated yet. Please launch startup evaluation to generate the strategic blueprint.")
        return

    # Header with Download PDF Button
    h_col1, h_col2 = st.columns([3, 1])
    with h_col1:
        st.markdown(
            """
            <div>
                <h1 style="color: #FFFFFF; font-size: 1.8rem; font-weight: 700; margin: 0;">
                    Startup Blueprint
                </h1>
                <p style="color: #94A3B8; font-size: 0.9rem; margin-top: 4px;">
                    Complete business plan and strategic architecture generated by your AI co-founder team.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with h_col2:
        pdf_bytes = ReportService.generate_startup_pdf(startup, analysis, roadmap)
        st.download_button(
            label="📥 Download PDF",
            data=pdf_bytes,
            file_name=f"{startup.name.lower().replace(' ', '_')}_blueprint.pdf",
            mime="application/pdf",
            type="primary",
            **get_width_kwargs(True),
        )

    st.markdown("<div style='height: 12px;'></div>", unsafe_allow_html=True)

    # Blueprint Layout: Left Index, Right Content
    b_col1, b_col2 = st.columns([1, 2.8], gap="medium")

    blueprint_sections = [
        "1. Executive Summary",
        "2. Problem Statement",
        "3. Proposed Solution",
        "4. Target Market & Personas",
        "5. Competitor Analysis & Moats",
        "6. Defensible USP",
        "7. Business Model",
        "8. Revenue Mechanics",
        "9. Core Product Features",
        "10. Dynamic Execution Roadmap",
        "11. Multi-Dimensional Risk Analysis",
        "12. Lead Co-Founder Assessment",
    ]

    with b_col1:
        st.markdown(
            """
            <div style="font-size: 0.82rem; font-weight: 700; color: #94A3B8; text-transform: uppercase; margin-bottom: 8px;">
                Blueprint Index
            </div>
            """,
            unsafe_allow_html=True,
        )
        selected_section = st.radio(
            "Blueprint Index",
            options=blueprint_sections,
            label_visibility="collapsed",
        )

    with b_col2:
        score = analysis.overall_score if analysis else 76
        verdict = analysis.feasibility_verdict if analysis else "Good Potential"

        # Top summary cards (matching reference screen)
        m1, m2, m3 = st.columns(3)
        with m1:
            st.markdown(
                f"""
                <div class="category-metric-card">
                    <div style="font-size: 0.7rem; color: #64748B; font-weight: 700;">STARTUP NAME</div>
                    <div style="font-size: 0.95rem; font-weight: 700; color: #FFFFFF; margin-top: 2px;">{startup.name}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with m2:
            st.markdown(
                f"""
                <div class="category-metric-card">
                    <div style="font-size: 0.7rem; color: #64748B; font-weight: 700;">TARGET MARKET</div>
                    <div style="font-size: 0.95rem; font-weight: 700; color: #FFFFFF; margin-top: 2px;">{startup.target_customer}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with m3:
            bm_label = (analysis.business_model[:24] + "...") if (analysis and analysis.business_model) else "Subscription + Commission"
            st.markdown(
                f"""
                <div class="category-metric-card">
                    <div style="font-size: 0.7rem; color: #64748B; font-weight: 700;">BUSINESS MODEL</div>
                    <div style="font-size: 0.95rem; font-weight: 700; color: #FFFFFF; margin-top: 2px;">{bm_label}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

        st.markdown("<div style='height: 8px;'></div>", unsafe_allow_html=True)

        # Dynamic Section Content Pane
        st.markdown(
            f"""
            <div class="venture-card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px;">
                    <div style="font-size: 1.25rem; font-weight: 700; color: #FFFFFF;">
                        {selected_section}
                    </div>
                    <div style="background: rgba(16, 185, 129, 0.15); border: 1px solid rgba(16, 185, 129, 0.3);
                                color: #10B981; padding: 4px 12px; border-radius: 9999px;
                                font-size: 0.8rem; font-weight: 600;">
                        Feasibility: {score}/100 ● {verdict}
                    </div>
                </div>
            """,
            unsafe_allow_html=True,
        )

        # Render corresponding section
        if "Executive Summary" in selected_section:
            exec_text = (
                analysis.executive_summary
                if (analysis and analysis.executive_summary)
                else f"{startup.name} is an AI-powered platform addressing market needs in {startup.country}."
            )
            st.markdown(f"<div style='color: #E2E8F0; line-height: 1.6;'>{exec_text}</div>", unsafe_allow_html=True)
            st.markdown("<div style='height: 14px;'></div>", unsafe_allow_html=True)
            st.markdown("#### Key Highlights")
            highlights = (
                analysis.key_advantages
                if (analysis and analysis.key_advantages)
                else [
                    "Strong localized market positioning and low customer acquisition costs",
                    "High demand for affordable, on-demand options among target demographics",
                    "Rapid engineering cycle with capital-efficient architecture",
                    "Estimated break-even threshold reachable within 6 months of operations",
                ]
            )
            for h in highlights:
                st.markdown(f"<div style='color: #10B981; margin-bottom: 4px;'>✓ <span style='color: #F8FAFC;'>{h}</span></div>", unsafe_allow_html=True)

        elif "Problem Statement" in selected_section:
            prob = analysis.problem_statement if (analysis and analysis.problem_statement) else startup.idea
            st.markdown(f"**Customer Problem:**\n\n{prob}")

        elif "Proposed Solution" in selected_section:
            sol = analysis.solution_statement if (analysis and analysis.solution_statement) else startup.idea
            st.markdown(f"**Venture Solution:**\n\n{sol}")

        elif "Target Market" in selected_section:
            st.markdown(f"**Primary Market:** {startup.target_market}")
            st.markdown(f"**Customer Persona:** {startup.target_customer}")
            st.markdown(f"**Geographic Scope:** {startup.country}")

        elif "Competitor Analysis" in selected_section:
            st.markdown(f"**Market Positioning:** {analysis.technical_direction or 'Focused niche differentiation.'}")

        elif "Defensible USP" in selected_section:
            usp_val = analysis.usp if (analysis and analysis.usp) else "Defensible hyper-local batch delivery economics."
            st.markdown(f"**Unique Selling Proposition:**\n\n{usp_val}")

        elif "Business Model" in selected_section:
            bm_val = analysis.business_model if (analysis and analysis.business_model) else "Platform fee + subscriptions."
            st.markdown(f"**Operating Model:**\n\n{bm_val}")

        elif "Revenue Mechanics" in selected_section:
            rm_val = analysis.revenue_model if (analysis and analysis.revenue_model) else "Tiered monthly plans."
            st.markdown(f"**Revenue Model:**\n\n{rm_val}")

        elif "Core Product Features" in selected_section:
            feats = analysis.core_features if (analysis and analysis.core_features) else [
                "Feature 1: Customer Discovery & Authentication",
                "Feature 2: Real-time Batch Routing Engine",
                "Feature 3: Frictionless Mobile Payments",
                "Feature 4: Live Order & Campus Logistics Dashboard",
            ]
            st.markdown("#### Initial Core Build Scope")
            for f in feats:
                st.markdown(f"• **{f}**")

        elif "Dynamic Execution Roadmap" in selected_section:
            duration = roadmap.total_duration_days if roadmap else 45
            st.markdown(f"**Calibrated Venture Duration:** {duration} Days")
            if roadmap and roadmap.milestones:
                st.markdown("#### Strategic Milestones")
                for m in roadmap.milestones:
                    st.markdown(f"- **Day {m.get('day')}:** {m.get('title')}")

        elif "Multi-Dimensional Risk Analysis" in selected_section:
            st.markdown("#### Risk Analysis & Mitigation Matrix")
            if analysis and analysis.risk_analysis:
                for r_name, r_body in analysis.risk_analysis.items():
                    if isinstance(r_body, dict):
                        st.markdown(
                            f"**{r_name.replace('_', ' ').title()}** (Impact: *{r_body.get('impact', 'Medium')}*):\n"
                            f"- *Description:* {r_body.get('description', '')}\n"
                            f"- *Mitigation:* {r_body.get('mitigation', '')}\n"
                        )
            else:
                st.write("Risk analysis synthesized in overview.")

        elif "Lead Co-Founder Assessment" in selected_section:
            st.markdown(f"**Difficulty Level:** {analysis.difficulty_level if analysis else 'MEDIUM'}")
            st.markdown(f"**Reasoning:** {analysis.difficulty_reasoning if analysis else 'Standard startup development hurdles.'}")
            st.markdown("#### Immediate Next Steps")
            steps = analysis.recommended_next_steps if (analysis and analysis.recommended_next_steps) else [
                "Conduct 10 discovery interviews",
                "Build initial prototype",
                "Launch closed pilot",
            ]
            for step in steps:
                st.markdown(f"✓ {step}")

        st.markdown("</div>", unsafe_allow_html=True)
