"""
Reports Screen.
Provides one-click generation and instant download of the complete ReportLab PDF dossier.
"""
from typing import Optional
import streamlit as st
from database.models import Startup, StartupAnalysis, DynamicRoadmap
from services.report_service import ReportService
from ui.styles import render_html, get_width_kwargs


def render_reports_view(
    startup: Optional[Startup],
    analysis: Optional[StartupAnalysis],
    roadmap: Optional[DynamicRoadmap],
):
    """
    Renders the Report Generation and Export screen.
    """
    render_html(
        """
        <div style="margin-bottom: 24px;">
            <h1 style="color: #FFFFFF; font-size: 1.8rem; font-weight: 700; margin: 0;">
                Executive Dossier & PDF Reports
            </h1>
            <p style="color: #94A3B8; font-size: 0.9rem; margin-top: 4px;">
                Download complete, investor-ready Venture Blueprints generated by ReportLab.
            </p>
        </div>
        """
    )

    if not startup:
        st.info("Please select or create a startup venture to generate executive reports.")
        return

    if not analysis:
        st.info(f"Venture analysis for '{startup.name}' has not been completed yet. Please run startup evaluation to generate the official executive dossier.")
        return

    col1, col2 = st.columns([1.8, 1.2], gap="large")

    with col1:
        render_html(
            f"""
            <div class="welcome-hero">
                <div style="font-size: 1.3rem; font-weight: 700; color: #FFFFFF; margin-bottom: 6px;">
                    {startup.name} – Complete Venture Blueprint
                </div>
                <div style="color: #94A3B8; font-size: 0.85rem; margin-bottom: 16px;">
                    Multi-page executive publication containing market sizing, competitor moats,
                    12-month unit economics, tech stack architecture, risk matrices, and dynamic execution roadmap.
                </div>
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 0.82rem; margin-bottom: 20px;">
                    <div>• Executive Summary & Opportunity</div>
                    <div>• 12-Month Cashflow & Burn Forecast</div>
                    <div>• 6-Dimension Category Scorecard</div>
                    <div>• Multi-Dimensional Risk Matrix</div>
                    <div>• Core Product Feature Architecture</div>
                    <div>• Calibrated Execution Roadmap</div>
                </div>
            </div>
            """
        )

        with st.spinner("Generating official ReportLab PDF dossier..."):
            pdf_bytes = ReportService.generate_startup_pdf(startup, analysis, roadmap)

        st.download_button(
            label=f"📥 Download {startup.name} Blueprint PDF",
            data=pdf_bytes,
            file_name=f"{startup.name.lower().replace(' ', '_')}_venture_blueprint.pdf",
            mime="application/pdf",
            type="primary",
            **get_width_kwargs(True),
        )

    with col2:
        render_html(
            f"""
            <div class="venture-card">
                <div class="stat-label">Document Specifications</div>
                <div style="margin-top: 10px; font-size: 0.85rem; color: #E2E8F0; line-height: 1.8;">
                    <b>Format:</b> Adobe PDF (ReportLab 5.0)<br>
                    <b>Document Version:</b> 1.0 (Production)<br>
                    <b>Target Market:</b> {startup.target_market}<br>
                    <b>Calibrated Roadmap:</b> {roadmap.total_duration_days if roadmap else 'Calibrated'} Days<br>
                    <b>Feasibility Score:</b> {analysis.overall_score}/100<br>
                    <b>Security:</b> Confidential Venture Analysis
                </div>
            </div>
            """
        )
